name: connectify
description: "Api connector meant to handle API requests with error and session management for Hapnium mobile platforms."

publish_to: none

version: 0.2.7
homepage: https://github.com/Hapnium/flutter/tree/main/connectify
repository: https://github.com/Hapnium/flutter/tree/main/connectify

environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.8.0+1

  tracing:
    path: ../tracing