name: sedat
description: A secured database for Hapnium platforms.

publish_to: none

version: 0.2.2
homepage: https://github.com/Hapnium/flutter/tree/main/sedat
repository: https://github.com/Hapnium/flutter/tree/main/sedat

environment:
  sdk: ^3.0.0

dependencies:
  hive_ce_flutter: ^2.3.1
  meta: ^1.16.0

  tracing:
    path: ../tracing
  hapnium:
    path: ../hapnium

dev_dependencies:
  hive_ce_generator: ^1.9.1
  test: ^1.26.1
