name: socket_client
description: "Websocket connector handling requests with error and session management for Hapnium platforms."

publish_to: none

version: 0.1.8
homepage: https://github.com/Hapnium/flutter/tree/main/websocket_flutter
repository: https://github.com/Hapnium/flutter/tree/main/websocket_flutter

environment:
  sdk: ^3.0.0

dependencies:
  stomp_dart_client: ^2.1.3

  tracing:
    path: ../tracing