name: phosphor_flutter
description: Implementation of Phosphoricons for Flutter. 772 icons and counting. Thin, Light, Regular, Bold, Fill.
version: 2.1.1
repository: https://github.com/Hapnium/flutter

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: PhosphorBold
      fonts:
        - asset: lib/fonts/Phosphor-Bold.ttf
          weight: 400
    - family: PhosphorDuotone
      fonts:
        - asset: lib/fonts/Phosphor-Duotone.ttf
          weight: 400
    - family: PhosphorFill
      fonts:
        - asset: lib/fonts/Phosphor-Fill.ttf
          weight: 400
    - family: PhosphorLight
      fonts:
        - asset: lib/fonts/Phosphor-Light.ttf
          weight: 400
    - family: PhosphorThin
      fonts:
        - asset: lib/fonts/Phosphor-Thin.ttf
          weight: 400
    - family: PhosphorRegular
      fonts:
        - asset: lib/fonts/Phosphor.ttf
          weight: 400
  assets:
    - assets/icons/regular/
    - assets/icons/thin/
    - assets/icons/light/
    - assets/icons/bold/
    - assets/icons/fill/
    - assets/icons/duotone/
    - meta/
