name: hapnium
description: A starting point for Dart libraries or applications.

publish_to: none

version: 0.0.8
homepage: https://github.com/Hapnium/flutter/tree/main/hapnium
repository: https://github.com/Hapnium/flutter/tree/main/hapnium

environment:
  sdk: ^3.7.0

dev_dependencies:
  test: ^1.26.1
