name: multimedia
description: A Flutter plugin that retrieves images and videos from mobile native multimedia.

publish_to: none

version: 0.1.15
homepage: https://github.com/Hapnium/flutter/tree/main/multimedia
repository: https://github.com/Hapnium/flutter/tree/main/multimedia

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  file_picker: ^10.1.9

  gallery:
    path: ../gallery

dev_dependencies:
  tracing:
    path: ../tracing
  smart:
    path: ../smart