name: zap
description: "HTTP and Socket client handling requests with error and session management for Hapnium platforms."

publish_to: none

version: 0.1.3
homepage: https://github.com/Hapnium/flutter/tree/main/zap
repository: https://github.com/Hapnium/flutter/tree/main/zap

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1
  
  tracing:
    path: ../tracing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0